{
  "microphones": [],
  "cameras": [],
  "printers": [],
  "desktop_aliases": {
    "notepad": {
      "type": "program",
      "target": "notepad.exe"
    },
    "explorer": {
      "type": "program",
      "target": "explorer.exe"
    },
    "browser": {
      "type": "url",
      "target": "https://www.google.com"
    },
    "steam": {
      "type": "url",
      "target": "steam://open/main"
    }
  },
  "allowed_paths": [
    "%USERPROFILE%\\\\Desktop",
    "%USERPROFILE%\\\\Documents"
  ],
  "recent": {
    "enabled": true,
    "max_items": 25
  },
  "registered_commands": {
    "open_downloads": {
      "type": "program",
      "target": "explorer.exe",
      "args": [
        "%USERPROFILE%\\\\Downloads"
      ]
    },
    "open_steam": {
      "type": "url",
      "target": "steam://open/main",
      "args": []
    },
    "open_browser": {
      "type": "url",
      "target": "https://www.google.com",
      "args": []
    }
  },
  "home_assistant": {
    "entities": []
  }
}
